
// const { getQuizzesByUserId } = require('../queries/ListofQuizzeswithUser');
//const { getQuestionsForQuiz } = require('../queries/getQuestionsForQuiz');
//const { getCorrectAnswers } = require('../queries/correctAnswers');
//const { getQuizResultById } = require('../queries/retrievingQuizResult');


 //const quizId = 2; // Replace with the actual quiz ID you want to retrieve questions for
 //getQuestionsForQuiz(quizId)
  //.then(questions => {
    //console.log('Questions for quiz:', questions);
   //})
   //.catch(error => {
   // console.error('Error:', error);
  // });

// const quizId = 2;
// getTypesofQuizzes(quizId)
//   .then(name => {
//     console.log('Types of quizzes:', name);
//   })
//   .catch(error => {
//     console.log('error:', error);
//   })

//const quizId = 2; // Replace with the actual quiz ID you want to retrieve questions for
// getCorrectAnswers(quizId)
//  .then(answers => {
//     console.log('Answers to questions:', answers);
//  })
//   .catch(error => {
//    console.error('Error:', error);
//   });

// const userId = 1;
// getQuizzesByUserId(userId)
//   .then(quizzes => console.log('Quizzes for user:', quizzes))
//   .catch(error => console.error('Error:', error.message));


// // Example usage with user_id
// const quizResult = {
//   quizzes_id: 1,
//   user_id: 1,
//   score: 70,
// };

// enablePgcryptoExtension()
//   .then(() => {
//     updateQuizResult(quizResult)
//       .then(resultId => console.log('Quiz result updated. Result ID:', resultId))
//       .catch(error => console.error('Error:', error.message));
//   })
//   .catch(error => console.error('Error:', error.message));

//resultId is the UUIDgenerated by pgcrypto


// const resultId = 14;

// getQuizResultById(resultId)
//   .then(result => {
//    console.log('Quiz Result:', result);
//  })
//   .catch(error => {
//     console.error('Error:', error.message);
//   });
